### ISSUE TITLE
Can't get the assigned job of an asset.

### ISSUE THREAD

**Issue by fahadwajed** [NerdCats/TaskCat#39]
Can't get the list of assigned job using this path
http://gofetch.cloudapp.net/api/Account/{asset_id}/jobs

**Comment by thehoneymad** [comment]
I see you're trying.  Can you please post what the TaskCat response was?
And please use taskcatdev for latest TaskCat release features. Preferably TaskCat 0.1.3.+ versions

**Comment by fahadwajed** [comment]
It returns the json but the data field is empty.
`{"pagination":{"Total":0,"Page":0,"Start":1,"PageSize":10,"TotalPages":0,"Returned":0},"data":[]}`

**Comment by thehoneymad** [comment]
Is it from taskcatdev?

**Comment by fahadwajed** [comment]
No. It's from gofetch.cloudapp.net

**Comment by thehoneymad** [comment]
Please try against taskcatdev, gofetch is pretty old as I presume. Meanwhile I would be looking

**Comment by thehoneymad** [comment]
Checked out the bug. Convincing indeed. There are few things are in need.

### What was done
1. You should check the swagger doc for the api first. I think you missed that by default it fetches last 5 days worth of result and only upto IN_PROGRESS state. Right now the **Next build** that would be hosted in TaskCat dev will not care about the datetime property and would return all results based on the query. 
2. The param name for providing dateTime to fetch the jobs from a certain is renamed to  _fromDateTime_. Now if you dont provide a date it will fetch all results. Its always good to provide a datetime to fetch from so the result generation is faster.
3. Every datetime parameter in TaskCat should be sent as a ISO-8601 DateTimeString format and should be url encoded if sent in the parameter.

Hope that would solve your problem, check out on the appveyor notification of the next build. Hopefully that would solve your problem.

P.S. If you encounter a serialization exception thats probably because of the new address format we are supporting in user profiles. You can delete all the jobs in taskcatdev and proceed or you can create a ticket for supporting legacy address types. In the latter case it will take a while to fix. 

Thanks. Let me know how your test comes out and posting a test result in a table would be really helpful for me

**Comment by thehoneymad** [comment]
Closing this issue, please reopen if the solutions stated above fails.
