### ISSUE TITLE
In delivery order, shouldn't we have separate text input fields for recipient's Name, Address and Phone to better represent the info?

### ISSUE THREAD

**Issue by faisalgobd** [NerdCats/TaskCat#93]
I have come to know that there are new fields in classified delivery orders like buyer and seller info.

**Comment by thehoneymad** [comment]
Um.... not necessarily for a generic delivery order. I still dont see the point of that to be honest. First of all, its always us who is selling or a vendor when it is for a generic delivery order. Not the same case for Classified delivery.

**Comment by tareq89** [comment]
![capture](https://cloud.githubusercontent.com/assets/4245521/17581369/29015f44-5fc7-11e6-9fe8-afcd878fad89.JPG)


I think what @faisalgobd tried to mean was, the Delivery type orders are now used by vendors like ZuumZuum, The Jar etc.

When they fill up the delivery address info, they dont have a field to mention the recipient/end customer names and phone number. So, what they do is mention the customer name. phonenumber along with the delivery address.

Now, we can not ensure that the vendors, when filling up a delivery order form, will mention the recipient/end customer names and phone number in a proper format.

Giving them recipient/end customer names and phone number field ensures that everything is in proper format.

For Classified delivery orders, this issue is solved by adding buyer and seller info.
I think this issue is related with #67

**Comment by thehoneymad** [comment]
Technically that delivery type should change or we should be able to classify those somehow. We can introduce a new payload for basic deliveries like we did in classified delivery workflow. Or we can modify classified delivery workflow to work with both. This invoice was meant for end clients, not enterprise users. And yes, we can populate the name field and phone number field. But for b2c end clients this can be automatically fetched from database. :) Thus is basic delivery payload which was basically intended for b2c customers don't have a name or any field like that in From or To fields.

**Comment by tareq89** [comment]
understood, thanks, should we create a feature issue for new payload?

**Comment by thehoneymad** [comment]
Yes, that would be ideal.

**Comment by tareq89** [comment]
Jira Issue GFETCH-164
